### ISSUE TITLE
Convert 2000 GOP Presidential Primary Election spreadsheet with town-level results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nh#1]
Using this [Excel file](http://sos.nh.gov/WorkArea/DownloadAsset.aspx?id=3082), extract the information in county-specific sheets into a CSV file. The "jurisdiction" column can represent a town or a ward within a town. Some candidate names you'll probably need to search for. 

Things to know:
- Output file is named 20000201__nh__republican__primary__president__precinct.csv
- Headers should be: county, jurisdiction, candidate, party, office, district, votes
- Each candidate results gets its own line.
- Only include candidate totals, don't include overall totals.

**Comment by palewire** [comment]
![I got this](http://gifsec.com/wp-content/uploads/GIF/2014/05/I-got-this-reaction-gif.gif)

**Comment by jessezlotoff** [comment]
I'm most of the way through converting this but not sure what I should use for "district" here.

**Comment by dwillis** [comment]
@jessezlotoff thanks! district can remain blank.

**Comment by jessezlotoff** [comment]
Thanks @dwillis.  What's the best way to upload the finished file?

**Comment by dwillis** [comment]
@jessezlotoff You can do a [pull request](https://help.github.com/articles/about-pull-requests/) or just send the finished file to openelections@gmail.com.
