### ISSUE TITLE
Scraper for 2016 General Election Precinct Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nh#7]
Using [the Excel files published by the state](http://sos.nh.gov/2016GenResults.aspx), create a single statewide CSV file with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

For the following offices: President, U.S. Senate, U.S. House, State Senate, State House. 

In the case of New Hampshire, the `precinct` is typically a town or village name.

**Comment by timtrice** [comment]
I can take care of this. Is there a timeframe?

**Comment by dwillis** [comment]
@timtrice Thanks! Whatever timeframe works for you works for us.

**Comment by lephead** [comment]
I'll make one also.  This state's house is crazy.

**Comment by dwillis** [comment]
@timtrice any update on this?

**Comment by dwillis** [comment]
I've got this.
